sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  include:
    - php: 5.6
    - php: 7
    - php: hhvm
  allow_failures:
    - php: hhvm

notifications:
  email: false

before_install:
  - composer self-update

install:
  - travis_retry composer install --no-interaction --ignore-platform-reqs --prefer-source

script:
  - ./vendor/bin/phpunit